GET http://localhost:8080/api/items
# Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODA2NDI1NSwiZXhwIjoxNzY4MTAwMjU1fQ.Ltb7jIwyLJmOX6-NKEnjnM2ON33fkVVcOKWimh0_3n3vHRu0wGRVU34I8_CQnIIjlxdjQ9R1R0BdD5ZWqbRYUlO3u7ApuBmcR1b6ZiBHN11HN15lsknSmYWYr6NtuLwXftwYXwDmacl21gLuzpjTkeR3OMkRai3c1tdA8WKu_8HXskWtXYJLCyq2Y1rz9CSgDTplFy1ry-ta34Ff0Jn1S7L3pi5yVWN-VZtq4tryJTOX5ANssSiB_PVF3K-GWkbh8byqbOIiBbb-_1Gml_wvwp35qH4oWLQqf2zjPQ0WI3m-tQdCL_Yl7O4Mm1EHINebtFrNfbHZS7Lgv0X6UYzhIQ