spring.application.name=EcommerceApplication
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=your_new_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# application.properties
spring.security.debug=true
logging.level.org.springframework.security=DEBUG
logging.level.com.example.ecommerce.security=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
