### View all orders (Admin) - paginated (page=0,size=50)
GET http://localhost:8080/api/admin/orders?page=0&size=50
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODE3Njg5NiwiZXhwIjoxNzY4MjEyODk2fQ.qpNFELCoFoNDlRp-0jxCGcOePucXQ0A4GKJROwuf0PWoY_zHWP4NFnPC8vtaLeVjyHgNPtVliLk2jyRnQPZn5TrdvKyCyR4R1eWbC3Uf5VI9Dh6_pwWBpp9SENULJxuEHPdrXXkQniLkE7nZrfK_7EV94PdcwrGvG2zGxEPAvUEaWKAfYOJxT2JLw3P7XyRhoap0foj3aKyPZ7lOwgaWlO6eDQMSQgTwwFBXvcCUNaDGOcfimShc5FgWv88Vl9DBX2FH1WSFgisXRxEPoUUm5B8aXT3dgeoY52WPS82I9_-8EHJTPtW7Gkp7tS1t97lxOgfBwVgUZEKkTAiOmPUOfQ
Accept: application/json