POST http://localhost:8080/api/user/payments/simulate
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MzU1MjE1LCJleHAiOjE3NjgzOTEyMTV9.KA6rMWV4l8OCSCJ0ublhyV0UlSbM1jGXBig9LH5f7A6GQvMNakrKmGsFpjYwv9bSBon_atLjtSBpXiuQ5hdScZbD4dH3oeWn2m6Gf8Eo4f6rSj74zc_z5PwDSnNXpMiKSvVi3-cC3Ip3IccIGWZv4oUYCy-MHKqLbBiUkE4LQTxuh6JF9SGE9pTh8jcl1abbz8u9IyVBcstPtVO3HwmEsxvvwc1oBp6zJb4ww9dPdHfm_Cm7DPGtK5JemL1gj0QmhPe8v-SgnIZY0Tir5lm2qO7SkLRsa-a7vuLi2Xkg87dMDOCozh8M-O1-cw79tNVA1zxBj8HfsVUD80Dc_PJef
Content-Type: application/json
Accept: application/json

{
  "cardNumber": "4242424242424242",
  "expiryMonth": 12,
  "expiryYear": 2028,
  "cvv": "911",
  "amount": 89.99
}
