POST http://localhost:8080/api/auth/logout
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTc3OTk3OTQxNSwiZXhwIjoxNzgwMDE1NDE1fQ.jiFHCNI5iGVttBtbB0rsn798YRTmO87JEs5iomfELSFPUaVJ0tstbFmkIgTzqVYzZu0TLSIFbEFJsavabzJTsjYflZ674mXm8J9Rxhcuw4pp6Tuol6IRk5AFzEBuiySb0wNf0vk_zvHA5ZiU_S3n114R6GwgOUR8aM96I4G89hj4lSLr30_sKyMkQAyg9qtWKRrqU0hGKITPF2dDn9MRGdIk28X0ZbD6_db9MPviJZane62SJK2Ljeblrq7rAcItLqBmQMOzdcjYxxZyrImU2R4iZQGU1RNzbjcfjBR6GViAKniB9ndzFLXoWPjcu5KOqrXAcZwFCCQtMH2SEZ5SgA