### Get order detail
GET http://localhost:8080/api/user/orders/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImlhdCI6MTc2ODE0NzMwNSwiZXhwIjoxNzY4MTgzMzA1fQ.jvRJAfX8yZjdaTpAEJBPD1pVQjkODXeDa4hwygs_qBTNkbJy8IndaVfP4XCOxwvTFG4_ERn-jQRhF5OoRItJOv4h86eKpEt-_0HvJESlHKZII-nIAGB7FGyVCLJvVi09c-bSqtKA2fR1sygNGaJFCCR4dAO5jok0XB8b3rQI_eSFqTJs2-wUkV-5TXooQCRBcsrbMLJpztemvP7Y1JGryjedDe6O3odAT7fUWoSWAq4A5RH9VtTOk4juBUlz31lqqR8YDSzI-vE5U52bxFYAsaSGnoK-fzhB1L_YG0EOIp6NuDuBUBmNVtSLjyWE8qCahmxIGhh5OcK3Ru5DhYuPHA