PUT http://localhost:8080/api/user/orders/3/pay
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzY4MTc0ODg0LCJleHAiOjE3NjgyMTA4ODR9.s6gxhb3lMPZfV7OyeBLhXRg1aZnERV3anELluDBnrihkUEoML714KymlGXp-KUTMoE3ot6zsns64N4HdXEf2RvfPvDJJmcvSHmxocRG_HzEE-HJTsxqwjgSPc9bXBdNDyU0k0O9cRxm1q-l7Gg99Z2R1pGZLyRpKbzrE2DkpC6YH1l4ocrFptxwl4aWYiywMDPTVLLxr_rpSYgCG6_e11azVKJckiDixVzamg-1sKMv-jOCI_FhrI5KDRUHjKoRrR9ozWETok1LoRid2zupDxSmm6Xjfp6rGqMCcWJA9HzvGeLFH4fpFMv7UpekyIpU-5goAGfDD7_SGs4nin2YJ0A
Content-Type: application/json

{
    "method": "WALLET",
    "cardId": 2
}