PUT http://localhost:8080/api/user/orders/1/pay
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzgxOTc2Mjk3LCJleHAiOjE3ODIwMTIyOTd9.KMjyk6SW2PUM4DGrX7cEr0OXrSYzFSngwtGbxlNdtY1VKtc5Zm6IFmokBJWUuHY2S-53pb9GmfB7Km-8CDduBNeXTZuNvOTZaYXWOSb_y1svGeCb6hZu_l4D4866xNfUcN7qh1CpSOc_Wud1NyVHrCevto9bj1zLs2etTPCdvShIvNxN316jvbQDXXNBQzQX589S_we1D780Go2-WfEAb5_M0A1f76gjwf1tqpA0jktYFryjQt-UOfNYv-2XGf31HkgEnlP0Gm2Xl3bpHx9O9FikejvC2SF0tEEPuCQPhAg5dH30i_nYGgEs5jApkDOeD6_5yd2ZukXuOLR3xf8iZQ
Content-Type: application/json

{
    "method": "WALLET",
    "cardId": 2
}